### ISSUE TITLE
wrong permissions for /dev/null /dev/full

### ISSUE THREAD

**Issue by leahneukirchen** [ghedo/pflask#1]
Here, pflask created a /dev/null with wrong permissions:

```
crw-r--r-- 1 root root   1, 7 Mar  3 18:09 full
crw-r--r-- 1 root root   1, 3 Mar  3 18:09 null
```

These files should be writable for group and others as well.

**Comment by ghedo** [comment]
Should be fixed now, thanks for reporting.
