### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Anachron** [ghedo/pflask#12]
I found this project and it really seems to be what I'm looking forward. Just wondering if its still maintained?

**Comment by ghedo** [comment]
Well, it's not really dead, but I haven't had a whole lot of free time in the last few months. If you have any bug report feel free to send it my way (and even send patches!) but don't expect any new features any time soon.

**Comment by Anachron** [comment]
hey @ghedo thank you for your quick reply! I am happy to know this project is not dead but rather feature-complete (for now). I will give it a try and open any issues that I may find.
