### ISSUE TITLE
Feature request: support file bind mounts

### ISSUE THREAD

**Issue by kergoth** [ghedo/pflask#3]
Bind mounting works for both files and directories, but pflask assumes that bind mounts are directories. This would be useful for things like /etc/resolv.conf, if one wants to avoid sudo cp'ing files like that into the container (the resolv.conf bind mount is default in systemd-nspawn, actually).

**Comment by ghedo** [comment]
Should be fixed in master, thanks for reporting.

> the resolv.conf bind mount is default in systemd-nspawn

I think newer nspawn versions copy resolv.conf into the container https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L1543
